### ISSUE TITLE
is it safe to use this addon with others addons?

### ISSUE THREAD

**Issue by RodrigoVieira19** [lambdadog/passfail2#10]
hello, sorry for the stupid question but I would like to know if this addon modifies the settings of other anki addons.
I am using the addon "Straight Reward" and unfortunately it does not have the option to hide the buttons. so I would like to use your addon combined with Straight Reward but I am afraid it will have a conflict..

**Comment by lambdadog** [comment]
This certainly isn't a stupid question, especially since they actually very nearly manage to cause an issue with each other!

That said, they do seem to be compatible, by the skin of their teeth, but I'll definitely be looking into implementing the conflicting piece of functionality in a less-conflicting way, since I hadn't forseen this kind of issue.
